name: Tjoskar
description: Code and other stuff
meta_description: "Tjoskar's blogg"

markdown: redcarpet
redcarpet:
    extensions: ['tables']

pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Oskar Karlsson'
